display: ":0"
xauthority: "~/.Xauthority"

global:
  minikube: false
  operator: true
  exposeAllDS: true  # Expose All Tango Services to the external network (enable Loadbalancer service)
  annotations:
    app.gitlab.com/app: ska-mid-cbf-fhs-system-tests
    app.gitlab.com/env: ska
  sub-system:
    ska-tango-base:
      enabled: false  # disabled to prevent deployment conflicts
    boogie:
      enabled: false
  retry:
    - "--sleep=3"
    - "--tries=100"
  tango_host: databaseds-tango-base:10000
  device_server_port: 45450
  cluster_domain: cluster.local

ska-tango-base:
  enabled: true
  vnc:
    enabled: false
  tangorest:
    enabled: false
  tangodb:
    use_pv: true

ska-tango-util:
  enabled: true

# Note: Versions and repository links defined here do not necessarily reflect what will be
# deployed to the namespace. These values can be overwritten by Makefile processing at runtime
# based on USE_DEV_BUILD and <repo>_HASH_VERSION variables.
ska-mid-cbf-fhs-vcc:
  enabled: true
  midcbf:
    image:
      registry: registry.gitlab.com/ska-telescope/ska-mid-cbf-fhs-vcc
      image: ska-mid-cbf-fhs-vcc
      tag: 0.0.1-dev.c1d8f5c2c
      pullPolicy: Always
      
  simulationMode: 0
  emulationMode: 1

  emulatorIds: 
    - "fhs-vcc-emulator-1"
    - "fhs-vcc-emulator-2"
    - "fhs-vcc-emulator-3"
    - "fhs-vcc-emulator-4"
    - "fhs-vcc-emulator-5"
    - "fhs-vcc-emulator-6"
    
  emulatorIpBlockIds:
    mac200: "ethernet_200g"
    packetValidation: "packet_validation"
    widebandInputBuffer: "wideband_input_buffer"
    widebandFrequencyShifter: "wideband_frequency_shifter"
    b123Vcc: "b123vcc"
    frequencySliceSelection: "fs_selection_26_2_1"

  instances:
    - name: fhs-vcc-1
      packetValidation:
        deviceId: 1
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 0 }}"
      mac200:
        deviceId: 1
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 0 }}"
      b123VccOsppfbChanneliser:
        deviceId: 1
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 0 }}"
      frequencySliceSelection:
        deviceId: 1
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 0 }}"
      widebandFrequencyShifter:
        deviceId: 1
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 0 }}"
      widebandInputBuffer:
        deviceId: 1
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 0 }}"
      vccAllBands:
        deviceId: 1
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
    - name: fhs-vcc-2
      packetValidation:
        deviceId: 2
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 1 }}"
      mac200:
        deviceId: 2
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 1 }}"
      b123VccOsppfbChanneliser:
        deviceId: 2
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 1 }}"
      frequencySliceSelection:
        deviceId: 2
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 1 }}"
      widebandFrequencyShifter:
        deviceId: 2
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 1 }}"
      widebandInputBuffer:
        deviceId: 2
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 1 }}"
      vccAllBands:
        deviceId: 2
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
    - name: fhs-vcc-3
      packetValidation:
        deviceId: 3
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 2 }}"
      mac200:
        deviceId: 3
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 2 }}"
      b123VccOsppfbChanneliser:
        deviceId: 3
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 2 }}"
      frequencySliceSelection:
        deviceId: 3
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 2 }}"
      widebandFrequencyShifter:
        deviceId: 3
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 2 }}"
      widebandInputBuffer:
        deviceId: 3
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 2 }}"
      vccAllBands:
        deviceId: 3
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
    - name: fhs-vcc-4
      packetValidation:
        deviceId: 4
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 3 }}"
      mac200:
        deviceId: 4
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 3 }}"
      b123VccOsppfbChanneliser:
        deviceId: 4
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 3 }}"
      frequencySliceSelection:
        deviceId: 4
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 3 }}"
      widebandFrequencyShifter:
        deviceId: 4
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 3 }}"
      widebandInputBuffer:
        deviceId: 4
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 3 }}"
      vccAllBands:
        deviceId: 4
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
    - name: fhs-vcc-5
      packetValidation:
        deviceId: 5
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 4 }}"
      mac200:
        deviceId: 5
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 4 }}"
      b123VccOsppfbChanneliser:
        deviceId: 5
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 4 }}"
      frequencySliceSelection:
        deviceId: 5
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 4 }}"
      widebandFrequencyShifter:
        deviceId: 5
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 4 }}"
      widebandInputBuffer:
        deviceId: 5
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 4 }}"
      vccAllBands:
        deviceId: 5
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
    - name: fhs-vcc-6
      packetValidation:
        deviceId: 6
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 5 }}"
      mac200:
        deviceId: 6
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 5 }}"
      b123VccOsppfbChanneliser:
        deviceId: 6
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 5 }}"
      frequencySliceSelection:
        deviceId: 6
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 5 }}"
      widebandFrequencyShifter:
        deviceId: 6
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 5 }}"
      widebandInputBuffer:
        deviceId: 6
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"
        emulatorId: "{{ index .Values.emulatorIds 5 }}"
      vccAllBands:
        deviceId: 6
        simulationMode: "{{ .Values.simulationMode }}"
        emulationMode: "{{ .Values.emulationMode }}"

  lowLevel:
    bitstreamEmulatorConfigPath: "emulators/config.json"
    emulatorBaseUrl: "ska-mid-cbf-fhs-system-tests.svc.cluster.local:5001"
    firmwareRegistry: https://artefact.skao.int/repository/raw-internal
    firmwareImage: ska-mid-cbf-agilex-vcc
    bitstreamId: agilex-vcc
    firmwareVersion: 0.0.9
    bitstreamPath: "/app/mnt/bitstream"

ska-mid-cbf-fhs-vcc-boogie:
  enabled: false  # TODO figure out boogie deployment/registry
  boogie:
    tango_host: databaseds-tango-base:10000
  image:
    repository: docker.io/library
    image: ska-mid-cbf-fhs-vcc-boogie
    tag: 0.0.1
    pullPolicy: IfNotPresent

ska-mid-cbf-emulators:
  enabled: true
  emulator:
    app_label: ska-mid-cbf-fhs-system-tests
    image:
      repository: registry.gitlab.com/ska-telescope/ska-mid-cbf-emulators/ska-mid-cbf-emulators-emulator
      tag: 0.5.3
      pullPolicy: Always
    verbosity: 3
  injector:
    app_label: ska-mid-cbf-fhs-system-tests
    image:
      repository: registry.gitlab.com/ska-telescope/ska-mid-cbf-emulators/ska-mid-cbf-emulators-injector
      tag: 0.5.3
      pullPolicy: Always
  
  emulators:
    - bitstream_emulator_id: agilex-vcc
      bitstream_emulator_ver: 0.0.9
      deployment_id: fhs-vcc-emulator-1
    - bitstream_emulator_id: agilex-vcc
      bitstream_emulator_ver: 0.0.9
      deployment_id: fhs-vcc-emulator-2
    - bitstream_emulator_id: agilex-vcc
      bitstream_emulator_ver: 0.0.9
      deployment_id: fhs-vcc-emulator-3
    - bitstream_emulator_id: agilex-vcc
      bitstream_emulator_ver: 0.0.9
      deployment_id: fhs-vcc-emulator-4
    - bitstream_emulator_id: agilex-vcc
      bitstream_emulator_ver: 0.0.9
      deployment_id: fhs-vcc-emulator-5
    - bitstream_emulator_id: agilex-vcc
      bitstream_emulator_ver: 0.0.9
      deployment_id: fhs-vcc-emulator-6

  rabbitmq:
    host: rabbitmq-service.ska-mid-cbf-fhs-system-tests.svc.cluster.local
