display: ":0"
xauthority: "~/.Xauthority"

global:
  minikube: false
  operator: true
  exposeAllDS: true  # Expose All Tango Services to the external network (enable Loadbalancer service)
  annotations:
    app.gitlab.com/app: ska-mid-cbf-fhs-system-tests
    app.gitlab.com/env: ska
  sub-system:
    ska-tango-base:
      enabled: false  # disabled to prevent deployment conflicts
    boogie:
      enabled: false
  retry:
    - "--sleep=3"
    - "--tries=100"
  tango_host: databaseds-tango-base:10000
  device_server_port: 45450
  cluster_domain: cluster.local

ska-tango-base:
  enabled: true
  vnc:
    enabled: false
  tangorest:
    enabled: false
  tangodb:
    use_pv: true

ska-tango-util:
  enabled: true

# Note: Versions and repository links defined here do not necessarily reflect what will be
# deployed to the namespace. These values can be overwritten by Makefile processing at runtime
# based on USE_DEV_BUILD and <repo>_HASH_VERSION variables.
ska-mid-cbf-fhs-vcc:
  enabled: true
  midcbf:
    image:
      registry: registry.gitlab.com/ska-telescope/ska-mid-cbf-fhs-vcc
      image: ska-mid-cbf-fhs-vcc
      tag: 0.0.2-dev.ce8dc774e
      pullPolicy: Always
      
  lowLevel:
    bitstreamEmulatorConfigPath: "emulators/config.json"
    emulatorBaseUrl: "ska-mid-cbf-fhs-system-tests.svc.cluster.local:5001"
    firmwareRegistry: https://artefact.skao.int/repository/raw-internal
    firmwareImage: ska-mid-cbf-agilex-vcc
    bitstreamId: agilex-vcc
    bitstreamVersion: 0.0.11
    bitstreamPath: /app/mnt/bitstream
    gitlab_bitstream_url_override: "https://gitlab.com/ska-telescope/ska-mid-cbf-bitstreams/-/archive/cip-3104-injections/ska-mid-cbf-bitstreams-cip-3104-injections.tar.gz?path=raw/ska-mid-cbf-agilex-vcc"
  
  properties:
    - name: deviceId
    - name: deviceVersionNum
      default: "0.0.2"
    - name: deviceGitlabHash
      default: "0"
    - name: configLocation
      default: "/app/mnt/lowLevelConfigMap"
    - name: simulationMode
      default: "0"
    - name: emulationMode
      default: "1"
    - name: emulatorIpBlockId
    - name: emulatorId
    - name: firmwareIpBlockId

  instances:
    - name: fhs-vcc-1
      deviceId: "1"
      emulatorId: "fhs-vcc-emulator-1"
    - name: fhs-vcc-2
      deviceId: "2"
      emulatorId: "fhs-vcc-emulator-2"
    - name: fhs-vcc-3
      deviceId: "3"
      emulatorId: "fhs-vcc-emulator-3"
    - name: fhs-vcc-4
      deviceId: "4"
      emulatorId: "fhs-vcc-emulator-4"
    - name: fhs-vcc-5
      deviceId: "5"
      emulatorId: "fhs-vcc-emulator-5"
    - name: fhs-vcc-6
      deviceId: "6"
      emulatorId: "fhs-vcc-emulator-6"


ska-mid-cbf-fhs-vcc-boogie:
  enabled: false  # TODO figure out boogie deployment/registry
  boogie:
    tango_host: databaseds-tango-base:10000
  image:
    repository: docker.io/library
    image: ska-mid-cbf-fhs-vcc-boogie
    tag: 0.0.2
    pullPolicy: IfNotPresent

ska-mid-cbf-emulators:
  enabled: true
  emulator:
    app_label: ska-mid-cbf-fhs-system-tests
    image:
      repository: registry.gitlab.com/ska-telescope/ska-mid-cbf-emulators/ska-mid-cbf-emulators-emulator
      tag: 0.5.4
      pullPolicy: Always
    verbosity: 3
  injector:
    app_label: ska-mid-cbf-fhs-system-tests
    image:
      repository: registry.gitlab.com/ska-telescope/ska-mid-cbf-emulators/ska-mid-cbf-emulators-injector
      tag: 0.5.4
      pullPolicy: Always
  
  emulators:
    - bitstream_emulator_id: agilex-vcc
      bitstream_emulator_ver: 0.0.11
      deployment_id: fhs-vcc-emulator-1
    - bitstream_emulator_id: agilex-vcc
      bitstream_emulator_ver: 0.0.11
      deployment_id: fhs-vcc-emulator-2
    - bitstream_emulator_id: agilex-vcc
      bitstream_emulator_ver: 0.0.11
      deployment_id: fhs-vcc-emulator-3
    - bitstream_emulator_id: agilex-vcc
      bitstream_emulator_ver: 0.0.11
      deployment_id: fhs-vcc-emulator-4
    - bitstream_emulator_id: agilex-vcc
      bitstream_emulator_ver: 0.0.11
      deployment_id: fhs-vcc-emulator-5
    - bitstream_emulator_id: agilex-vcc
      bitstream_emulator_ver: 0.0.11
      deployment_id: fhs-vcc-emulator-6

  rabbitmq:
    host: rabbitmq-service.ska-mid-cbf-fhs-system-tests.svc.cluster.local
