display: ":0"
xauthority: "~/.Xauthority"

global:
  minikube: false
  operator: true
  exposeAllDS: true # Expose All Tango Services to the external network (enable Loadbalancer service)
  annotations:
    app.gitlab.com/app: ska-mid-cbf-fhs-system-tests
    app.gitlab.com/env: ska
  sub-system:
    ska-tango-base:
      enabled: false # disabled to prevent deployment conflicts
    boogie:
      enabled: false
  retry:
    - "--sleep=3"
    - "--tries=100"
  tango_host: databaseds-tango-base:10000
  device_server_port: 45450
  cluster_domain: cluster.local

ska-tango-base:
  enabled: true
  vnc:
    enabled: false
  tangorest:
    enabled: false
  tangodb:
    use_pv: true

ska-tango-util:
  enabled: true

# Note: Versions and repository links defined here do not necessarily reflect what will be
# deployed to the namespace. These values can be overwritten by Makefile processing at runtime
# based on USE_DEV_BUILD and <repo>_HASH_VERSION variables.
ska-mid-cbf-fhs-vcc:
  enabled: true
  midcbf:
    image:
      registry: registry.gitlab.com/ska-telescope/ska-mid-cbf-fhs-vcc
      image: ska-mid-cbf-fhs-vcc
      tag: 0.1.0-dev.cc5d87970
      pullPolicy: Always

  bitstreamMountPath: "/app/mnt/bitstream"

  properties:
    deviceId: ""
    deviceVersionNum: "0.1.0"
    deviceGitlabHash: "0"
    simulationMode: "0"
    emulationMode: "1"
    emulatorBaseUrl: "ska-mid-cbf-fhs-system-tests.svc.cluster.local:5001"
    bitstreamPath: &bitstreamPath "/app/mnt/bitstream"
    bitstreamId: "agilex-vcc"
    bitstreamVersion: "0.0.16"
    emulatorId: &emulatorId "fhs-vcc-emulator-{{.deviceId}}"
    emulatorIpBlockId: ""
    firmwareIpBlockId: ""
    healthMonitorPollInterval: "3"

  instances: &deviceInstances
    - name: fhs-vcc-1
      deviceId: "1"
    - name: fhs-vcc-2
      deviceId: "2"
    - name: fhs-vcc-3
      deviceId: "3"
    - name: fhs-vcc-4
      deviceId: "4"
    - name: fhs-vcc-5
      deviceId: "5"
    - name: fhs-vcc-6
      deviceId: "6"
    - name: fhs-vcc-7
      deviceId: "7"
    - name: fhs-vcc-8
      deviceId: "8"
    - name: fhs-vcc-9
      deviceId: "9"
    - name: fhs-vcc-10
      deviceId: "10"
    - name: fhs-vcc-11
      deviceId: "11"
    - name: fhs-vcc-12
      deviceId: "12"
    - name: fhs-vcc-13
      deviceId: "13"
    - name: fhs-vcc-14
      deviceId: "14"
    - name: fhs-vcc-15
      deviceId: "15"
    - name: fhs-vcc-16
      deviceId: "16"
    - name: fhs-vcc-17
      deviceId: "17"
    - name: fhs-vcc-18
      deviceId: "18"
    - name: fhs-vcc-19
      deviceId: "19"
    - name: fhs-vcc-20
      deviceId: "20"
    - name: fhs-vcc-21
      deviceId: "21"
    - name: fhs-vcc-22
      deviceId: "22"
    - name: fhs-vcc-23
      deviceId: "23"

ska-mid-cbf-fhs-vcc-boogie:
  enabled: true
  boogie:
    tango_host: databaseds-tango-base:10000

ska-mid-cbf-emulators:
  enabled: true
  emulator:
    app_label: ska-mid-cbf-fhs-system-tests
    image:
      repository: registry.gitlab.com/ska-telescope/ska-mid-cbf-emulators/ska-mid-cbf-emulators-emulator
      tag: 0.7.0
      pullPolicy: Always
    verbosity: 3
  injector:
    app_label: ska-mid-cbf-fhs-system-tests
    image:
      repository: registry.gitlab.com/ska-telescope/ska-mid-cbf-emulators/ska-mid-cbf-emulators-injector
      tag: 0.7.0
      pullPolicy: Always

  properties:
    bitstreamPath: *bitstreamPath
    bitstreamId: "agilex-vcc"
    bitstreamVersion: "0.0.16"
    emulatorId: *emulatorId

  instances: *deviceInstances

  rabbitmq:
    host: rabbitmq-service.ska-mid-cbf-fhs-system-tests.svc.cluster.local
